/**
 * @fileoverview Internationalization (i18n) module for agentrc CLI
 * @module lib/i18n
 */

export type SupportedLanguage = 'en' | 'es';

let currentLanguage: SupportedLanguage = 'en';

/**
 * Available languages with their display names
 */
export const LANGUAGES: Record<SupportedLanguage, string> = {
  en: 'English',
  es: 'Español'
};

type TranslationDictionary = Record<string, string>;

/**
 * Translation dictionaries
 */
const dictionaries: Record<SupportedLanguage, TranslationDictionary> = {
  en: {
    // CLI Header
    'init.header': 'Initializing AI Agent environment configuration',
    'init.targetDir': 'Target directory:',
    'init.modeForce': 'FORCE mode: will overwrite existing files',
    'init.modeNonInteractive': 'NON-INTERACTIVE mode',
    'init.modeDryRun': 'DRY-RUN mode (simulation only)',
    
    // Prompts
    'prompt.selectLanguage': 'Select language / Selecciona idioma:',
    'prompt.selectEditors': 'Which editors/agents do you want to configure?',
    'prompt.selectInitType': 'Select initialization type:',
    
    // Init types
    'init.quickStart': 'Quick start (recommended) - Creates .context/ + AGENTS.md',
    'init.customBridges': 'Custom bridges (advanced)',
    'init.bridgesNotNeeded': 'Note: Most modern editors read AGENTS.md directly. Bridges are rarely needed now.',
    
    // Spinners
    'spinner.creatingContext': 'Creating .context/ structure...',
    'spinner.contextCreated': '.context/ structure created',
    'spinner.copyingTemplates': 'Copying template files...',
    'spinner.templatesCopied': 'Templates copied',
    'spinner.generatingBridges': 'Generating bridge files...',
    'spinner.bridgesGenerated': '{count} bridge files generated',
    'prompt.bootstrap': 'Do you want to generate an AI Setup Prompt? (Helps your AI learn this project)',
    'init.bootstrapGenerated': 'Created AI_BOOTSTRAP.md - Pass this file to your AI agent to setup the project.',
    
    // Summary
    'summary.simulationComplete': 'SIMULATION COMPLETE',
    'summary.runWithoutDryRun': 'Run without --dry-run to apply changes.',
    'summary.initComplete': 'INITIALIZATION COMPLETE!',
    'summary.projectConfigured': 'Project configured at:',
    'summary.nextSteps': 'Next steps:',
    'summary.step1': '1. Edit .context/architecture.md with your actual stack',
    'summary.step2': '2. Adjust .context/rules/coding-standards.md',
    'summary.step3': '3. Add specific skills in .context/skills/',
    
    // Errors
    'error.initFailed': 'Error during initialization',
    
    // Bridge file comments
    'bridge.generatedBy': 'Generated by agentrc v{version}',
    'bridge.readAgents': 'Always read \'AGENTS.md\' to understand the global context.',
    'bridge.resources': 'Resources:',
    'bridge.architecture': 'Architecture:',
    'bridge.rules': 'Rules:',
    'bridge.skills': 'Skills:',
    'bridge.docs': 'Docs:',
    'bridge.projectExpert': 'Project Expert',
    'bridge.projectExpertDesc': 'Expert mode with project context',
    'bridge.claudeIntro': 'You are a senior expert developer working on this project.',
    'bridge.claudeReadContext': 'Before generating code, read and understand the context:',
    'bridge.principles': 'Principles',
    'bridge.followRules': 'Strictly follow the rules defined in .context/rules/',
    'bridge.usePatterns': 'Use the patterns documented in skills',
    'bridge.maintainConsistency': 'Maintain consistency with existing architecture',
    'bridge.copilotContext': 'Project Context',
    'bridge.copilotContextDesc': 'This project uses a centralized context structure in `.context/`.',
    'bridge.copilotInstructions': 'Instructions',
    'bridge.copilotReadAgents': 'Read `AGENTS.md` for context index',
    'bridge.copilotFollowRules': 'Follow the rules in `.context/rules/coding-standards.md`',
    'bridge.copilotUsePatterns': 'Use patterns from `.context/skills/` when applicable',
    'bridge.mainRules': 'Main Rules',
    'bridge.useStrictTS': 'Use strict TypeScript (no `any`)',
    'bridge.followNaming': 'Follow project naming conventions',
    'bridge.addErrorHandling': 'Add appropriate error handling',
    'bridge.antigravityIntro': 'You are a senior expert developer working on this project. Review the context structure below before making changes.'
  },
  es: {
    // CLI Header
    'init.header': 'Iniciando configuración del entorno de Agente AI',
    'init.targetDir': 'Directorio destino:',
    'init.modeForce': 'Modo FORCE: sobrescribirá archivos existentes',
    'init.modeNonInteractive': 'Modo NO-INTERACTIVO',
    'init.modeDryRun': 'Modo DRY-RUN (solo simulación)',
    
    // Prompts
    'prompt.selectLanguage': 'Selecciona idioma / Select language:',
    'prompt.selectEditors': '¿Qué editores/agentes quieres configurar?',
    'prompt.selectInitType': 'Selecciona tipo de inicialización:',
    
    // Init types
    'init.quickStart': 'Inicio rápido (recomendado) - Crea .context/ + AGENTS.md',
    'init.customBridges': 'Bridges personalizados (avanzado)',
    'init.bridgesNotNeeded': 'Nota: La mayoría de editores modernos leen AGENTS.md directamente. Los bridges ya casi no son necesarios.',
    
    // Spinners
    'spinner.creatingContext': 'Creando estructura .context/...',
    'spinner.contextCreated': 'Estructura .context/ creada',
    'spinner.copyingTemplates': 'Copiando archivos de plantilla...',
    'spinner.templatesCopied': 'Plantillas copiadas',
    'spinner.generatingBridges': 'Generando archivos puente...',
    'spinner.bridgesGenerated': '{count} archivos puente generados',
    'prompt.bootstrap': '¿Quieres generar un Prompt de Configuración IA? (Ayuda a tu IA a aprender este proyecto)',
    'init.bootstrapGenerated': 'Creado AI_BOOTSTRAP.md - Pasa este archivo a tu agente IA para configurar el proyecto.',
    
    // Summary
    'summary.simulationComplete': 'SIMULACIÓN COMPLETADA',
    'summary.runWithoutDryRun': 'Ejecuta sin --dry-run para aplicar los cambios.',
    'summary.initComplete': '¡INICIALIZACIÓN COMPLETADA!',
    'summary.projectConfigured': 'Proyecto configurado en:',
    'summary.nextSteps': 'Próximos pasos:',
    'summary.step1': '1. Edita .context/architecture.md con tu stack real',
    'summary.step2': '2. Ajusta .context/rules/coding-standards.md',
    'summary.step3': '3. Añade skills específicas en .context/skills/',
    
    // Errors
    'error.initFailed': 'Error durante inicialización',
    
    // Bridge file comments
    'bridge.generatedBy': 'Generado por agentrc v{version}',
    'bridge.readAgents': 'Lee siempre \'AGENTS.md\' para entender el contexto global.',
    'bridge.resources': 'Recursos:',
    'bridge.architecture': 'Arquitectura:',
    'bridge.rules': 'Reglas:',
    'bridge.skills': 'Skills:',
    'bridge.docs': 'Docs:',
    'bridge.projectExpert': 'Experto del Proyecto',
    'bridge.projectExpertDesc': 'Modo experto con contexto del proyecto',
    'bridge.claudeIntro': 'Eres un desarrollador experto senior trabajando en este proyecto.',
    'bridge.claudeReadContext': 'Antes de generar código, lee y entiende el contexto:',
    'bridge.principles': 'Principios',
    'bridge.followRules': 'Sigue estrictamente las reglas definidas en .context/rules/',
    'bridge.usePatterns': 'Usa los patrones documentados en las skills',
    'bridge.maintainConsistency': 'Mantén consistencia con la arquitectura existente',
    'bridge.copilotContext': 'Contexto del Proyecto',
    'bridge.copilotContextDesc': 'Este proyecto utiliza una estructura de contexto centralizada en `.context/`.',
    'bridge.copilotInstructions': 'Instrucciones',
    'bridge.copilotReadAgents': 'Lee `AGENTS.md` para el índice de contexto',
    'bridge.copilotFollowRules': 'Sigue las reglas en `.context/rules/coding-standards.md`',
    'bridge.copilotUsePatterns': 'Usa los patrones de `.context/skills/` cuando aplique',
    'bridge.mainRules': 'Reglas Principales',
    'bridge.useStrictTS': 'Usa TypeScript estricto (sin `any`)',
    'bridge.followNaming': 'Sigue las convenciones de naming del proyecto',
    'bridge.addErrorHandling': 'Añade manejo de errores apropiado',
    'bridge.antigravityIntro': 'Eres un desarrollador experto senior trabajando en este proyecto. Revisa la estructura de contexto antes de hacer cambios.'
  }
};

/**
 * Get the current language
 */
export function getLanguage(): SupportedLanguage {
  return currentLanguage;
}

/**
 * Set the current language
 */
export function setLanguage(lang: SupportedLanguage): void {
  if (LANGUAGES[lang]) {
    currentLanguage = lang;
  }
}

/**
 * Translate a key to the current language
 */
export function t(key: string, params: Record<string, string | number> = {}): string {
  const dict = dictionaries[currentLanguage] || dictionaries.en;
  let text = dict[key] || dictionaries.en[key] || key;
  
  // Replace parameters like {count}, {version}
  for (const [param, value] of Object.entries(params)) {
    text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), String(value));
  }
  
  return text;
}

